name: Deploy to AWS EC2

on:
  push:
    branches: [ "master" ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH }}
        script: |
          cd ~/app || git clone https://github.com/durgesh4040/aws.git ~/app
          cd ~/app
          git pull origin master

          # For Node.js
          pm2 restart app || pm2 start index.js --name app

       
